# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "articles", :force => true do |t|
    t.column "user_id",      :integer
    t.column "title",        :string
    t.column "synopsis",     :text
    t.column "body",         :text
    t.column "published",    :boolean,  :default => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "published_at", :datetime
    t.column "category_id",  :integer,  :default => 1
  end

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "pages", :force => true do |t|
    t.column "title",      :string
    t.column "permalink",  :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer, :null => false
    t.column "user_id", :integer, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "username",        :string,   :limit => 64,  :default => "",   :null => false
    t.column "email",           :string,   :limit => 128, :default => "",   :null => false
    t.column "hashed_password", :string,   :limit => 64
    t.column "enabled",         :boolean,                 :default => true, :null => false
    t.column "profile",         :text
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "last_login_at",   :datetime
  end

  add_index "users", ["username"], :name => "index_users_on_username"

end
