# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 15) do

  create_table "articles", :force => true do |t|
    t.column "user_id",      :integer
    t.column "title",        :string
    t.column "synopsis",     :text
    t.column "body",         :text
    t.column "published",    :boolean,  :default => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "published_at", :datetime
    t.column "category_id",  :integer,  :default => 1
  end

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "comments", :force => true do |t|
    t.column "entry_id",    :integer
    t.column "user_id",     :integer
    t.column "guest_name",  :string
    t.column "guest_email", :string
    t.column "guest_url",   :string
    t.column "body",        :text
    t.column "created_at",  :datetime
  end

  add_index "comments", ["entry_id"], :name => "index_comments_on_entry_id"

  create_table "entries", :force => true do |t|
    t.column "user_id",        :integer
    t.column "title",          :string
    t.column "body",           :text
    t.column "comments_count", :integer,  :default => 0, :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  add_index "entries", ["user_id"], :name => "index_entries_on_user_id"

  create_table "forums", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :text
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "topics_count", :integer,  :default => 0, :null => false
  end

  create_table "pages", :force => true do |t|
    t.column "title",      :string
    t.column "permalink",  :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "posts", :force => true do |t|
    t.column "topic_id",   :integer
    t.column "user_id",    :integer
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "posts", ["topic_id"], :name => "index_posts_on_topic_id"

  create_table "roles", :force => true do |t|
    t.column "name", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer, :null => false
    t.column "user_id", :integer, :null => false
  end

  create_table "topics", :force => true do |t|
    t.column "forum_id",    :integer
    t.column "user_id",     :integer
    t.column "name",        :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "posts_count", :integer,  :default => 0, :null => false
  end

  add_index "topics", ["forum_id"], :name => "index_topics_on_forum_id"

  create_table "users", :force => true do |t|
    t.column "username",        :string,   :limit => 64,  :default => "",   :null => false
    t.column "email",           :string,   :limit => 128, :default => "",   :null => false
    t.column "hashed_password", :string,   :limit => 64
    t.column "enabled",         :boolean,                 :default => true, :null => false
    t.column "profile",         :text
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "last_login_at",   :datetime
    t.column "posts_count",     :integer,                 :default => 0,    :null => false
    t.column "entries_count",   :integer,                 :default => 0,    :null => false
    t.column "blog_title",      :string
    t.column "enable_comments", :boolean,                 :default => true
  end

  add_index "users", ["username"], :name => "index_users_on_username"

end
